server:
  port: 8801 # port 번호
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      # import.sql을 이용하여 초기 데이터 값을 받으려면 create로 변경하여야 함.
      ddl-auto: update # create : drop-create
    properties:
      # hibernate query console 에 출력
      hibernate.format_sql: true # 보기 좋게 바꿔줌
      hibernate.use_sql_comments: true # 추가적인 주석 표시
    defer-datasource-initialization: true # Hibernate에 의해 생성된 스키마에 초기값을 넣어주겠다는 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myvue?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://127.0.0.1:3307/myvue?serverTimezone=Asia/Seoul
    username: myvue
    password: myvue
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  mvc:
    static-path-pattern: /static/** # static path 경로
    pathmatch:
      matching-strategy: ant-path-matcher # swagger 호환 이슈
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  web:
    resources:
      cache:
        period: 0
      static-locations:
        - classpath:/static/
logging:
  level:
    root: info
    org.hibernate.SQL: debug # sql
    org.hibernate.type.descriptor.sql.BasicBinder: trace # input bind
    # org.hibernate.type.descriptor.sql.BasicExtractor: trace # output bind
    # org.springframework.security: trace # spring security log 범위 (기본 info)
    com.project.vue: debug # 해당 패키지의 log 범위 (TRACE > DEBUG > INFO > WARN > ERROR > FATAL)
admin:
  url: http://localhost:3000
site:
  upload: D:/W/bin/upload/file
  image: D:/W/bin/upload/image/
  temp-image: D:/W/bin/temp/image/
  crypto:
    secret-key: y/B?E(G+KbPeShVm
  jwt:
    token-expiration-min: 30 # 30분
    secret-key: MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhAJ9X81Pb5aZdhtPVz+v2Gu07saN7DfzaTkZaeY78arOlAgMBAAE=
api:
  public-data:
     service-key: Ah33nedGlORpg%2B8WYnFa3d%2BnzJ5PLyV5323uW%2FIYyy4uMvSMp7L%2Bk0hjW9%2BHn5ox11R06p2SWNQ8ENblZyrfkA%3D%3D

springfox: # Swagger-ui 설정
  documentation:
    swagger-ui:
      base-url: /custom-swagger
